# This file created by conda-build 2.0.7
# meta.yaml template originally from:
# /opt/recipe, last modified Mon Nov 28 18:36:38 2016
# ------------------------------------------------

package:
    name: samtools
    version: 1.3.1
source:
    fn: samtools-1.3.1.tar.bz2
    md5: a7471aa5a1eb7fc9cc4c6491d73c2d88
    url: https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
build:
    number: '5'
    skip: 'False'
requirements:
    build:
        - gcc
        - zlib
        - curl
    run:
        - libgcc
        - zlib
        - curl
test:
    commands:
        - samtools --help
about:
    home: https://github.com/samtools/samtools
    license: MIT
    summary: Tools for dealing with SAM, BAM and CRAM files


