{% set name = "ipyrad" %}
{% set version = "0.9.10" %}

package:
  name: {{name}}
  version: {{version}}

source:
  git_url: https://github.com/eaton-lab/{{name}}.git
  git_rev: {{version}}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python
  entry_points:
    - ipyrad = ipyrad.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
    - scipy
    - numpy
    - numba >=0.37
    - future
    - h5py
    - ipyparallel >=6.0.2
    - requests
    - cutadapt
    - pysam >=0.15
    - mpi4py >=3.0
    - bedtools
    - muscle
    - vsearch >=2.13
    - bwa

test:
  imports:
    - ipyrad
    - ipyrad.analysis
  commands:
    - ipyrad -h

about:
  home: http://github.com/dereneaton/ipyrad
  license: GPL3
  license_file: LICENSE.txt
  summary: Interactive assembly and analysis of RAD-seq data sets.
