name: ipyrad
channels: 
  - conda-forge
  - bioconda
  - ipyrad
  - eaton-lab
dependencies:
  - ipyrad
  - ipyparallel
  - ipcoal
  - toytree
  - raxml
  - mrbayes
  - structure
  - clumpp
#  - tetrad # Remove until we get a conda package for tetrad > python3.7
  - scikit-learn 
  - bcftools
  - htslib
  - bpp
  - bucky
  - treemix   # forces openblas on numpy/scipy
